In [40]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv('heart_disease.csv')
df

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

In [42]:
df.columns

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level', 'Heart Disease Status'],
      dtype='object')

In [43]:
df.isnull().sum()

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [44]:
df = df.drop([
    'Exercise Habits',
    'Alcohol Consumption',
    'Stress Level',
    'Sleep Hours',
    'Sugar Consumption'
], axis=1)

In [45]:
df

,Age,Gender,Blood Pressure,Cholesterol Level,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,High LDL Cholesterol,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,Yes,Yes,No,24.991591,Yes,No,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,No,Yes,Yes,25.221799,No,No,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,No,No,No,29.855447,No,Yes,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,Yes,Yes,No,24.130477,Yes,Yes,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Yes,Yes,Yes,20.486289,Yes,No,263.0,154.0,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Yes,No,No,18.788791,Yes,Yes,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,No,No,No,31.856801,Yes,Yes,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,Yes,No,Yes,26.899911,No,Yes,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Yes,No,Yes,34.964026,Yes,Yes,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Yes,Yes,Yes,25.111295,No,Yes,121.0,149.0,14.387810,6.208531,Yes

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Smoking               9975 non-null   object
 5   Family Heart Disease  9979 non-null   object
 6   Diabetes              9970 non-null   object
 7   BMI                   9978 non-null   float64
 8   High Blood Pressure   9974 non-null   object
 9   High LDL Cholesterol  9974 non-null   object
 10  Triglyceride Level    9974 non-null   float64
 11  Fasting Blood Sugar   9978 non-null   float64
 12  CRP Level             9974 non-null   float64
 13  Homocysteine Level    9980 non-null   float64
 14  Heart Disease Status  10000 non-null  object
dtypes: float64(8), object(7)
memory usage: 1.1+ MB

In [47]:
df.isnull().sum()

Age                     29
Gender                  19
Blood Pressure          19
Cholesterol Level       30
Smoking                 25
Family Heart Disease    21
Diabetes                30
BMI                     22
High Blood Pressure     26
High LDL Cholesterol    26
Triglyceride Level      26
Fasting Blood Sugar     22
CRP Level               26
Homocysteine Level      20
Heart Disease Status     0
dtype: int64

In [48]:
# Get all numeric columns
# select_dtypes() is used to select columns based on data types
numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns #choose integer and float format
print(numeric_columns)

# Get all categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns #object is text format
print(categorical_columns)


# Fill NaN values in numeric columns using median
for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median()) 

# Fill NaN values in categorical columns using mode
for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

Index(['Age', 'Blood Pressure', 'Cholesterol Level', 'BMI',
       'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level',
       'Homocysteine Level'],
      dtype='object')
Index(['Gender', 'Smoking', 'Family Heart Disease', 'Diabetes',
       'High Blood Pressure', 'High LDL Cholesterol', 'Heart Disease Status'],
      dtype='object')

In [49]:
df.isnull().sum()

Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Smoking                 0
Family Heart Disease    0
Diabetes                0
BMI                     0
High Blood Pressure     0
High LDL Cholesterol    0
Triglyceride Level      0
Fasting Blood Sugar     0
CRP Level               0
Homocysteine Level      0
Heart Disease Status    0
dtype: int64

In [50]:
## Convert categorical variables into numeric variables(True and False)
df = pd.get_dummies(df, drop_first=True)

# Convert boolean columns into integers
bool_columns = df.select_dtypes(include=['bool']).columns

for col in bool_columns:
    df[col] = df[col].astype(int) 
df

,Age,Blood Pressure,Cholesterol Level,BMI,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Gender_Male,Smoking_Yes,Family Heart Disease_Yes,Diabetes_Yes,High Blood Pressure_Yes,High LDL Cholesterol_Yes,Heart Disease Status_Yes
0,56.0,153.0,155.0,24.991591,342.0,120.0,12.969246,12.387250,1,1,1,0,1,0,0
1,69.0,146.0,286.0,25.221799,133.0,157.0,9.355389,19.298875,0,0,1,1,0,0,0
2,46.0,126.0,216.0,29.855447,393.0,92.0,12.709873,11.230926,1,0,0,0,0,1,0
3,32.0,122.0,293.0,24.130477,293.0,94.0,12.509046,5.961958,0,1,1,0,1,1,0
4,60.0,166.0,242.0,20.486289,263.0,154.0,10.381259,8.153887,1,1,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,136.0,243.0,18.788791,343.0,133.0,3.588814,19.132004,0,1,0,0,1,1,1
9996,38.0,172.0,154.0,31.856801,377.0,83.0,2.658267,9.715709,1,0,0,0,1,1,1
9997,73.0,152.0,201.0,26.899911,248.0,88.0,4.408867,9.492429,1,1,0,1,0,1,1
9998,23.0,142.0,299.0,34.964026,113.0,153.0,7.215634,11.873486,1,1,0,1,1,1,1
9999,38.0,128.0,193.0,25.111295,121.0,149.0,14.387810,6.208531,0,1,1,1,0,1,1

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Separate features and target variable
X = df.drop('Heart Disease Status_Yes', axis=1)
y = df['Heart Disease Status_Yes']

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Create StandardScaler object
scaler = StandardScaler()

# Fit and transform training data
X_train = scaler.fit_transform(X_train)

# Transform testing data
X_test = scaler.transform(X_test)

In [52]:
print(X_train.shape,
      X_test.shape,
      y_train.shape,
      y_test.shape)

(8000, 14) (2000, 14) (8000,) (2000,)